apiVersion: v1
kind: Namespace
metadata:
  name: webcpits
  labels:
    istio-injection:
      enabled

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: webcpits-pod
  namespace: webcpits
  labels:
    app: web-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        version: v1
    spec:
      containers:
      - name: web
        image: lauramamian/trendmicro-co:1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000

---

kind: Service
apiVersion: v1
metadata:
  name: webapp-svc
  namespace: webcpits
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 80
    # puerto del contenedor -> target port
      targetPort: 3000
      protocol: TCP
      nodePort: 31000